# Autostart Configuration

# Polkit agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# Bar
exec-once = waybar &

# Wallpaper daemon
exec-once = swww init &

# Idle daemon
exec-once = hypridle &

# Notifications
exec-once = dunst &

# Network applet
exec-once = nm-applet --indicator &
