# Window Rules

# Float pavucontrol
windowrule = float 1, match:class ^(pavucontrol)$

# Float network manager
windowrule = float 1, match:class ^(nm-connection-editor)$

# Float blueman
windowrule = float 1, match:class ^(blueman-manager)$

# Make kitty opaque if needed, or set blur
windowrule = opacity 0.9 0.9, match:class ^(kitty)$
